services:
  - type: web
    name: q-sat-ai
    env: python
    plan: free
    buildCommand: |
      echo "Python version:"
      python --version
      pip install -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
